# General GitHub Repository Settings
repository:
  license:       # Select a license from the options below
  
# MATLAB Toolbox Settings
matlab_toolbox:
  namespace_name: scalebar
  toolbox_name: scalebar
  author_name: Eivind Hennestad                     
  author_email:          
  author_company:
  toolbox_summary: Scalebar for images and plots
  toolbox_description: Create a scalebar object for x- and or y-axis. Scalebar appearance is configured on creation, through setting of properties, or interactively using a context menu.
  dependencies: MATLAB

# Publishing options
codecov:
  badge_token: null

fileexchange:
  fex_url: https://se.mathworks.com/matlabcentral/fileexchange/109114-scalebar-for-images-and-plots
